src/objects/LAB_Google_API_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>client_id__c</fullName>
        <label>client_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>redirect_uri__c</fullName>
        <inlineHelpText>https://c.na9.visual.force.com/apex/googleOauth2</inlineHelpText>
        <label>redirect_uri</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>scope__c</fullName>
        <inlineHelpText>https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fglass.timeline+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fglass.location</inlineHelpText>
        <label>scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LAB_Google_API_Settings</label>
</CustomObject>

src/objects/LAB_Google_Mirror_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Individual User Settings</description>
    <fields>
        <fullName>refresh_token__c</fullName>
        <inlineHelpText>automatically populated</inlineHelpText>
        <label>refresh_token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LAB_Google_Mirror_Settings</label>
</CustomObject>

src/classes/LAB_Mirror_Settings_Controller.cls
public class LAB_Mirror_Settings_Controller{

    public final LAB_Google_API_Settings__c apiSettings { get; private set; }
    public final LAB_Google_Mirror_Settings__c userSettings { get; private set; }

    public final Boolean apiSettingsReady { get; private set; }
    public final Boolean userSettingsReady { get; private set; }
    
    public LAB_Mirror_Settings_Controller() {
    	apiSettings = LAB_Google_API_Settings__c.getOrgDefaults();
        userSettings = LAB_Google_Mirror_Settings__c.getInstance(UserInfo.getUserId());
        apiSettingsReady = apiSettings != null && apiSettings.client_id__c != null;
        userSettingsReady = userSettings != null && userSettings.refresh_token__c != null;
    }
    
    public PageReference authorizeApp() {
        String url = 'https://accounts.google.com/o/oauth2/auth?' + 
            'scope=' + apiSettings.scope__c +
            '&state=%2Fprofile' +
            '&redirect_uri=' + EncodingUtil.urlEncode(apiSettings.redirect_uri__c, 'UTF-8') +  
            '&response_type=code' +
            '&client_id=' + apiSettings.client_id__c + 
            '&access_type=offline' +
            '&approval_prompt=force';
            
    	return new PageReference(url);  
    }
    
}