src/objects/LAB_Google_API_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>client_id__c</fullName>
        <label>client_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>client_secret__c</fullName>
        <label>client_secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>redirect_uri__c</fullName>
        <inlineHelpText>https://c.na9.visual.force.com/apex/googleOauth2</inlineHelpText>
        <label>redirect_uri</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>scope__c</fullName>
        <inlineHelpText>https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fglass.timeline+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fglass.location</inlineHelpText>
        <label>scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LAB_Google_API_Settings</label>
</CustomObject>

src/objects/LAB_Google_Mirror_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Individual User Settings</description>
    <fields>
        <fullName>access_token__c</fullName>
        <label>access_token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>refresh_token__c</fullName>
        <inlineHelpText>automatically populated</inlineHelpText>
        <label>refresh_token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LAB_Google_Mirror_Settings</label>
</CustomObject>

src/classes/LAB_Mirror_Test_Utility.cls
@isTest
public class LAB_Mirror_Test_Utility{
    /*
		useful when the settings need to exist, but we don't need them.
	*/
    public static void setupSettings() {
        LAB_Mirror_Test_Utility.getApiSettings();
        LAB_Mirror_Test_Utility.getUserSettings();
    }
    
    public static LAB_Google_API_Settings__c getApiSettings() {
    	LAB_Google_API_Settings__c apiSettings = new LAB_Google_API_Settings__c();
        apiSettings.client_id__c = 'mockclient';
        apiSettings.client_secret__c = 'mocksecret';
        apiSettings.redirect_uri__c = 'mockuri';
        apiSettings.scope__c = 'mockscope';
        apiSettings.SetupOwnerId = UserInfo.getOrganizationId();
        upsert apiSettings;       
        return apiSettings;
    }
    
    public static LAB_Google_Mirror_Settings__c getUserSettings() {
        LAB_Google_Mirror_Settings__c userSettings = new LAB_Google_Mirror_Settings__c();
     	userSettings.refresh_token__c = 'mockrefreshtoken';
        userSettings.access_token__c = 'mockaccesstoken';
        userSettings.SetupOwnerId = UserInfo.getUserId();
        upsert userSettings;
        return userSettings;
    }
}